version: '3.9' # optional since v1.27.0
services:
  api:
    container_name: nest_api
    build: .
    ports:
      # - '3000:3000'
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    image: postgres:13
    container_name: nest_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      # - '5432:5432'
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
