version: '3.9' # optional since v1.27.0
services:
  api:
    container_name: nest_api
    build: .
    ports:
      # - '3000:3000'
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules

  database:
    image: postgres:13
    container_name: nest_db
    restart: always
    environment:
      POSTGRES_DB: apiNest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
